"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
type Goal="survival"|"social"|"work"|"travel"; type Level="A0"|"A1"|"A2"; type Mode="text"|"voice"|"mixed";
const goals:[Goal,string,string,string][]=[
 ["survival","Giao tiếp thiết yếu","🏠","Gọi món, đi taxi, hỏi đường, thanh toán"],
 ["social","Kết bạn và đời sống","👋","Tự giới thiệu, kết bạn, trò chuyện sở thích"],
 ["work","Công việc","💼","Chào hỏi, nhờ hỗ trợ, họp và xin nghỉ"],
 ["travel","Du lịch","✈️","Di chuyển, ăn uống và xử lý tình huống phổ biến"],
];
const levels:[Level,string,string][]=[["A0","Mới bắt đầu","Chưa biết hoặc chỉ biết vài từ"],["A1","Biết một số câu","Có thể nói chào hỏi và câu rất ngắn"],["A2","Nói được câu đơn giản","Có thể xử lý hội thoại cơ bản"]];
const modes:[Mode,string,string][]=[["text","Ưu tiên gõ","⌨️"],["mixed","Gõ và nói","🔄"],["voice","Ưu tiên nói","🎤"]];
export default function OnboardingPage(){const router=useRouter();const[step,setStep]=useState(0);const[goal,setGoal]=useState<Goal|null>(null);const[level,setLevel]=useState<Level|null>(null);const[mode,setMode]=useState<Mode>("mixed");const[returning,setReturning]=useState(false);
useEffect(()=>{try{const p=JSON.parse(localStorage.getItem("chinese-mission-user")||"null");if(p?.onboardingCompleted){setReturning(true);setGoal(p.goal||null);setLevel(p.level||null);setMode(p.mode||"mixed")}}catch{}},[]);
const save=()=>{if(!goal||!level)return;localStorage.setItem("chinese-mission-user",JSON.stringify({id:"local-user",nativeLanguage:"vi",bridgeLanguage:"vi",goal,level,currentLevel:level,mode,preferredMode:mode,onboardingCompleted:true,createdAt:new Date().toISOString()}));router.push("/missions")};
return <div className="app-shell"><div className="mx-auto max-w-lg px-5 py-8"><div className="mb-8 flex gap-2">{[0,1,2].map(s=><div key={s} className={`h-1.5 flex-1 rounded-full ${s<=step?"bg-green-600":"bg-green-100"}`}/>)}</div>{returning&&<div className="mb-6 flex items-center justify-between rounded-xl border border-green-200 bg-green-50 p-4"><span className="text-sm text-green-900">Đã có tiến độ học trên thiết bị này.</span><button onClick={()=>router.push("/missions")} className="text-sm font-semibold text-green-800 underline">Tiếp tục học</button></div>}
{step===0&&<section className="space-y-6"><div><div className="inline-flex rounded-full bg-green-100 px-3 py-1 text-xs font-semibold text-green-800">Dạy bằng tiếng Việt</div><h1 className="mt-3 text-3xl font-bold text-green-950">Học tiếng Trung qua nhiệm vụ thực tế</h1><p className="mt-2 text-slate-600">Anh muốn ưu tiên mục tiêu nào trước?</p></div><div className="space-y-3">{goals.map(([v,l,i,d])=><button key={v} onClick={()=>{setGoal(v);setStep(1)}} className={`app-card flex w-full gap-4 p-4 text-left ${goal===v?"ring-2 ring-green-500":""}`}><span className="text-2xl">{i}</span><span><span className="block font-semibold text-green-950">{l}</span><span className="text-sm text-slate-500">{d}</span></span></button>)}</div></section>}
{step===1&&<section className="space-y-6"><div><h1 className="text-2xl font-bold text-green-950">Trình độ hiện tại</h1><p className="mt-2 text-slate-600">Mức này dùng để sắp xếp gợi ý và độ khó.</p></div><div className="space-y-3">{levels.map(([v,l,d])=><button key={v} onClick={()=>{setLevel(v);setStep(2)}} className={`app-card w-full p-4 text-left ${level===v?"ring-2 ring-green-500":""}`}><span className="font-semibold text-green-950">{v} · {l}</span><span className="mt-1 block text-sm text-slate-500">{d}</span></button>)}</div><button onClick={()=>setStep(0)} className="text-sm text-green-800">← Quay lại</button></section>}
{step===2&&<section className="space-y-6"><div><h1 className="text-2xl font-bold text-green-950">Cách luyện chính</h1><p className="mt-2 text-slate-600">Có thể đổi bất kỳ lúc nào trong hồ sơ.</p></div><div className="flex gap-3">{modes.map(([v,l,i])=><button key={v} onClick={()=>setMode(v)} className={`app-card flex-1 p-4 text-center ${mode===v?"ring-2 ring-green-500":""}`}><span className="block text-2xl">{i}</span><span className="mt-2 block text-sm font-semibold text-green-950">{l}</span></button>)}</div><div className="rounded-2xl border border-green-200 bg-green-50 p-4 text-sm text-green-900"><b>Bài đầu tiên:</b> gọi một ly latte nóng. Có chữ Hán, pinyin, nghĩa Việt, nghe mẫu, nhập giọng nói và gợi ý tăng dần.</div><button onClick={save} className="mint-button w-full py-4 text-lg font-semibold">Bắt đầu học →</button><button onClick={()=>setStep(1)} className="text-sm text-green-800">← Quay lại</button></section>}</div></div>}
