"use client";
import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import PracticePhraseCard from "@/components/PracticePhraseCard";
import { Paywall } from "@/components/Paywall";
import { canStartMission,consumeAttempt,getQuotaSummary } from "@/lib/entitlements";
import { getMission,getScenario } from "@/lib/data/scenarios";
import { getMissionObjectiveVi,getMissionTitleVi,getRoleVi,getScenarioNameVi,getSlotVi,getStyleVi } from "@/lib/i18n/vi";
import { recordStudyActivity } from "@/lib/storage";
import type { Mission,Scenario } from "@/lib/types";
export default function WarmupPage(){const params=useParams();const router=useRouter();const[mission,setMission]=useState<Mission|null>(null);const[scenario,setScenario]=useState<Scenario|null>(null);const[wall,setWall]=useState(false);
useEffect(()=>{const m=getMission(String(params.id));setMission(m||null);setScenario(m?getScenario(m.scenarioId)||null:null)},[params.id]);
if(!mission)return <div className="app-shell flex items-center justify-center"><div className="text-center"><p className="font-semibold text-green-950">Không tìm thấy bài học</p><button onClick={()=>router.push("/missions")} className="mt-3 text-green-800 underline">Về danh sách bài</button></div></div>;
const start=()=>{if(!canStartMission()){setWall(true);return}consumeAttempt();recordStudyActivity();router.push(`/missions/${mission.id}/chat`)};
return <div className="app-shell"><header className="border-b border-green-100 bg-white/90 px-5 py-4"><div className="mx-auto flex max-w-xl items-center gap-3"><button onClick={()=>router.push("/missions")} className="text-green-800">←</button><div><h1 className="font-bold text-green-950">{getMissionTitleVi(mission)}</h1><p className="text-xs text-slate-500">{scenario?getScenarioNameVi(scenario):""} · {mission.level} · {mission.estimatedMinutes} phút</p></div></div></header><main className="mx-auto max-w-xl space-y-6 px-5 py-6"><section className="rounded-2xl border border-green-200 bg-green-50 p-5"><div className="text-xs font-semibold uppercase tracking-wider text-green-700">Nhiệm vụ của anh</div><h2 className="mt-2 text-lg font-bold text-green-950">{getMissionObjectiveVi(mission)}</h2><div lang="zh" className="mt-1 text-sm text-green-700">{mission.objective}</div></section><section className="app-card flex items-center gap-4 p-4"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-green-100 text-xl">{scenario?.icon||"👤"}</div><div><div className="font-semibold text-green-950">Đối thoại với: {getRoleVi(mission)}</div><div className="text-xs text-slate-500">{getStyleVi(mission.npcPersona.style)}</div></div></section><section className="app-card p-4"><h3 className="font-semibold text-green-950">Các ý cần truyền đạt</h3><div className="mt-3 space-y-2">{mission.requiredSlots.map((s,i)=><div key={s} className="flex items-center gap-3 text-sm"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-green-100 font-bold text-green-800">{i+1}</span><span>{getSlotVi(s)}</span></div>)}</div>{mission.optionalSlots.length>0&&<div className="mt-3 text-xs text-slate-500">Ý mở rộng: {mission.optionalSlots.map(getSlotVi).join(", ")}</div>}</section><section><h3 className="mb-3 font-semibold text-green-950">Câu mẫu cần luyện</h3><div className="space-y-4">{mission.warmupPatterns.map((p,i)=><PracticePhraseCard key={i} pattern={p}/>)}</div></section><button onClick={start} className="mint-button w-full py-4 text-lg font-semibold">Bắt đầu hội thoại</button><p className="text-center text-xs text-slate-500">Có thể trả lời bằng chữ Hán, pinyin hoặc giọng nói. Tiếng Việt dùng làm ngôn ngữ hướng dẫn.</p></main>{wall&&<Paywall onClose={()=>setWall(false)} resetsAt={getQuotaSummary().resetsAt}/>}</div>}
