"use client";
import { useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { scenarios } from "@/lib/data/scenarios";
import { getMissionObjectiveVi,getMissionTitleVi,getScenarioNameVi } from "@/lib/i18n/vi";
import { getQuotaSummary } from "@/lib/entitlements";
import { getStudyStreak } from "@/lib/storage";

const category:{[k:string]:string}={survival:"Giao tiếp thiết yếu",social:"Giao tiếp xã hội",work:"Giao tiếp công việc",travel:"Du lịch"};
export default function MissionsPage(){const router=useRouter();const[done,setDone]=useState<string[]>([]);const[query,setQuery]=useState("");const[goal,setGoal]=useState("survival");const[mounted,setMounted]=useState(false);
useEffect(()=>{setMounted(true);try{const u=JSON.parse(localStorage.getItem("chinese-mission-user")||"null");if(!u?.onboardingCompleted){router.replace("/onboarding");return}setGoal(u.goal||"survival");setDone(JSON.parse(localStorage.getItem("chinese-mission-completed")||"[]"))}catch{router.replace("/onboarding")}},[router]);
const all=useMemo(()=>scenarios.flatMap(s=>s.missions.map(m=>({m,s}))),[]);const rec=all.find(({m})=>!done.includes(m.id));const ordered=useMemo(()=>[...scenarios].sort((a,b)=>Number(b.category===goal)-Number(a.category===goal)),[goal]);const q=mounted?getQuotaSummary():null;const filtered=(m:{id:string;title:string;titleEn:string})=>!query||`${getMissionTitleVi(m as never)} ${m.title} ${m.titleEn}`.toLowerCase().includes(query.toLowerCase());
return <div className="app-shell"><header className="sticky top-0 z-20 border-b border-green-100 bg-white/90 px-5 py-4 backdrop-blur"><div className="mx-auto flex max-w-2xl items-center justify-between gap-3"><div><h1 className="text-xl font-bold text-green-950">Chinese Mission Việt</h1><p className="text-xs text-green-700">{done.length}/{all.length} bài hoàn thành · 🔥 {mounted?getStudyStreak():0} ngày{q?<span> · còn {q.premium?"∞":q.remaining} lượt</span>:null}</p></div><nav className="flex gap-2 text-xs"><Link href="/phrasebook" className="rounded-lg bg-green-50 px-3 py-2 text-green-800">Sổ câu</Link><Link href="/profile" className="rounded-lg bg-green-50 px-3 py-2 text-green-800">Hồ sơ</Link></nav></div></header><main className="mx-auto max-w-2xl space-y-6 px-5 py-6"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm bài học hoặc tình huống…" className="w-full rounded-xl border border-green-200 bg-white px-4 py-3 outline-none focus:ring-2 focus:ring-green-400"/>
{rec&&<section className="mint-gradient rounded-3xl p-6 text-white shadow-lg"><div className="text-xs font-semibold uppercase tracking-wider text-green-100">Đề xuất tiếp theo</div><h2 className="mt-2 text-xl font-bold">{getMissionTitleVi(rec.m)}</h2><p className="mt-1 text-sm text-green-50">{getMissionObjectiveVi(rec.m)}</p><div className="mt-3 text-xs text-green-100">{rec.m.level} · khoảng {rec.m.estimatedMinutes} phút · {getScenarioNameVi(rec.s)}</div><Link href={`/missions/${rec.m.id}/warmup`} className="mt-5 inline-block rounded-xl bg-white px-5 py-3 font-semibold text-green-800">Bắt đầu nhiệm vụ</Link></section>}
{ordered.map(s=>{const ms=s.missions.filter(filtered);if(!ms.length)return null;return <section key={s.id}><div className="mb-3 flex items-end justify-between"><div><div className="text-xs font-semibold uppercase tracking-wider text-green-700">{category[s.category]}</div><h2 className="text-lg font-bold text-green-950">{s.icon} {getScenarioNameVi(s)}</h2></div><div className="text-xs text-slate-500">{s.missions.filter(m=>done.includes(m.id)).length}/{s.missions.length}</div></div><div className="app-card divide-y divide-green-100 overflow-hidden">{ms.map(m=><Link key={m.id} href={`/missions/${m.id}/warmup`} className={`flex items-center justify-between gap-4 p-4 hover:bg-green-50 ${done.includes(m.id)?"opacity-60":""}`}><div className="flex items-center gap-3"><div className={`flex h-8 w-8 items-center justify-center rounded-full text-sm ${done.includes(m.id)?"bg-green-600 text-white":"bg-green-100 text-green-700"}`}>{done.includes(m.id)?"✓":m.id.replace("m","")}</div><div><div className="font-semibold text-green-950">{getMissionTitleVi(m)}</div><div lang="zh" className="text-xs text-slate-500">{m.title}</div></div></div><div className="text-right text-xs text-slate-500"><div>{m.level}</div><div>{m.estimatedMinutes} phút</div></div></Link>)}</div></section>})}
<div className="grid grid-cols-2 gap-3"><Link href="/cloud" className="app-card p-4"><div className="font-semibold text-green-900">☁ Đồng bộ</div><div className="mt-1 text-xs text-slate-500">Supabase tùy chọn</div></Link><Link href="/profile" className="app-card p-4"><div className="font-semibold text-green-900">⚙ Cài đặt học</div><div className="mt-1 text-xs text-slate-500">Pinyin, nghĩa, tốc độ đọc</div></Link></div></main></div>}
