"use client";
import { useEffect,useState } from "react";
import { useParams,useRouter } from "next/navigation";
import DebriefCard from "@/components/DebriefCard";
import { getMission,scenarios } from "@/lib/data/scenarios";
import { generateDebrief } from "@/lib/engine/dialogue";
import { getMissionTitleVi } from "@/lib/i18n/vi";
import { recordStudyActivity } from "@/lib/storage";
import { getSlotItem, setSlotItem } from "@/lib/slots";
import type { DebriefResult,Mission,PhrasebookItem,Session,Turn } from "@/lib/types";
export default function DebriefPage(){const params=useParams();const router=useRouter();const[mission,setMission]=useState<Mission|null>(null);const[debrief,setDebrief]=useState<DebriefResult|null>(null);const[saved,setSaved]=useState(new Set<number>());const[ai,setAi]=useState(false);
useEffect(()=>{const m=getMission(String(params.id));if(!m)return;setMission(m);let raw:{turns?:Turn[];filledSlots?:string[];slotsFilledMap?:Record<string,string>;hintUsageCount?:number}={};try{raw=JSON.parse(getSlotItem(`chinese-mission-session-${m.id}`)||"{}") }catch{}const filled=raw.slotsFilledMap||Object.fromEntries((raw.filledSlots||[]).map(s=>[s,"filled"]));const session:Session={id:"debrief",missionId:m.id,status:"completed",currentState:"complete",slotsFilledMap:filled,turns:raw.turns||[],hintLevel:0,startedAt:new Date().toISOString()};const fallback=generateDebrief(m,session);setDebrief(fallback);const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),22000);fetch("/api/debrief",{method:"POST",headers:{"Content-Type":"application/json"},signal:controller.signal,body:JSON.stringify({missionId:m.id,session:{turns:raw.turns||[],slotsFilledMap:filled,hintUsageCount:raw.hintUsageCount||0}})}).then(r=>r.ok?r.json():Promise.reject()).then(r=>{setDebrief(r);setAi(Boolean(r.aiPowered))}).catch(()=>{}).finally(()=>clearTimeout(timer));let list:string[]=[];try{list=JSON.parse(getSlotItem("chinese-mission-completed")||"[]")}catch{};if(!list.includes(m.id)){list.push(m.id);setSlotItem("chinese-mission-completed",JSON.stringify(list))}recordStudyActivity()},[params.id]);
if(!mission||!debrief)return <div className="app-shell flex items-center justify-center"><div className="text-green-800">Đang tổng hợp kết quả…</div></div>;
const flat=scenarios.flatMap(s=>s.missions);const idx=flat.findIndex(m=>m.id===mission.id);const next=flat[idx+1];const save=(i:number)=>{const p=debrief.transferPatterns[i];if(!p)return;let items:PhrasebookItem[]=[];try{items=JSON.parse(getSlotItem("chinese-mission-phrasebook")||"[]")}catch{};if(!items.some(x=>x.textCn===p.hanzi))items.unshift({id:`pb-${Date.now()}-${i}`,textCn:p.hanzi,gloss:p,sourceMissionId:mission.id,masteryScore:0.2,savedAt:new Date().toISOString()});setSlotItem("chinese-mission-phrasebook",JSON.stringify(items));setSaved(v=>new Set(v).add(i))};
return <div className="app-shell"><header className="border-b border-green-100 bg-white/90 px-5 py-4"><div className="mx-auto max-w-xl"><h1 className="text-lg font-bold text-green-950">Kết quả: {getMissionTitleVi(mission)}</h1><p className="text-xs text-slate-500">{ai?"Phân tích bằng AI · hướng dẫn tiếng Việt":"Phân tích cục bộ · không cần API"}</p></div></header><main className="mx-auto max-w-xl px-5 py-6"><DebriefCard debrief={debrief} savedIndices={saved} onSaveExpression={save} onRetry={()=>router.push(`/missions/${mission.id}/warmup`)} onNextMission={()=>router.push(next?`/missions/${next.id}/warmup`:"/missions")}/></main></div>}
