import { NextRequest,NextResponse } from "next/server";
import { callAI,isAIConfigured,parseJSON } from "@/lib/engine/ai-client";
import { buildNpcPrompt,buildPolicyPrompt } from "@/lib/engine/prompts";
import { detectScript,processUserInput } from "@/lib/engine/dialogue";
import { getMission } from "@/lib/data/scenarios";
import { translateKnownChineseVi } from "@/lib/i18n/vi";
import type { Mission,Session } from "@/lib/types";
interface Body{missionId:string;userInput:string;session:{currentState:string;slotsFilledMap:Record<string,string>;turns:Array<{role:string;rawInput:string;npcReplyCn?:string;understood?:boolean;errorTags?:string[]}>;hintLevel:number}}
interface Policy{understood:boolean;user_intent_cn:string;user_intent_vi?:string;newly_filled_slots:string[];next_act:string;next_state:string;task_status:"in_progress"|"completed";error_tags:string[];hint_level_recommended:number}
interface Npc{reply_cn:string;reply_vi?:string;reply_en:string;emotion:string}
const sessionOf=(b:Body,m:Mission):Session=>({id:"api",missionId:m.id,status:"in_progress",currentState:b.session.currentState,slotsFilledMap:b.session.slotsFilledMap,turns:[],hintLevel:b.session.hintLevel,startedAt:new Date().toISOString()});
const rule=(b:Body,m:Mission)=>NextResponse.json({...processUserInput(b.userInput,m,sessionOf(b,m)),aiPowered:false});
export async function POST(request:NextRequest){let body:Body;try{body=await request.json()}catch{return NextResponse.json({error:"Dữ liệu gửi lên không hợp lệ"},{status:400})}const mission=getMission(body.missionId);if(!mission)return NextResponse.json({error:"Không tìm thấy nhiệm vụ"},{status:404});if(!isAIConfigured()||process.env.USE_RULE_ENGINE==="true")return rule(body,mission);try{const policyRaw=await callAI(buildPolicyPrompt(mission,sessionOf(body,mission),body.userInput,detectScript(body.userInput)),body.userInput);const policy=parseJSON<Policy>(policyRaw.content);const history=body.session.turns.slice(-6).map(t=>({role:t.role==="npc"?"assistant":t.role,content:t.npcReplyCn||t.rawInput}));history.push({role:"user",content:body.userInput});const npcRaw=await callAI(buildNpcPrompt(mission,policy,history),`Quyết định: ${JSON.stringify(policy)}`);const npc=parseJSON<Npc>(npcRaw.content);const slots={...body.session.slotsFilledMap};for(const s of policy.newly_filled_slots||[])if(mission.requiredSlots.includes(s)||mission.optionalSlots.includes(s))slots[s]="filled";const all=mission.requiredSlots.every(s=>s in slots);return NextResponse.json({normalizedUserCn:policy.user_intent_cn||body.userInput,understood:Boolean(policy.understood),taskStatus:all?"completed":policy.task_status||"in_progress",slotsFilled:Object.keys(slots),missingSlots:mission.requiredSlots.filter(s=>!(s in slots)),npcReplyCn:npc.reply_cn,npcReplyVi:npc.reply_vi||translateKnownChineseVi(npc.reply_cn,npc.reply_en),npcReplyEn:npc.reply_en,currentState:policy.next_state||body.session.currentState,errorTags:policy.error_tags||[],hintAvailable:true,aiPowered:true})}catch(e){console.error("AI chat failed; using rule engine",e);return rule(body,mission)}}
