import { NextRequest,NextResponse } from "next/server";
import { callAI,isAIConfigured,parseJSON } from "@/lib/engine/ai-client";
import { buildDebriefPrompt } from "@/lib/engine/prompts";
import { generateDebrief } from "@/lib/engine/dialogue";
import { getMission } from "@/lib/data/scenarios";
import type { DebriefResult,GlossItem,Session,Turn } from "@/lib/types";
interface Body{missionId:string;session:{turns:Array<Partial<Turn>&{role:string;rawInput:string}>;slotsFilledMap:Record<string,string>;hintUsageCount?:number}}
interface AIOut{result:"success"|"partial_success"|"failure";score:number;strengths:string[];top_fixes:Array<{type:string;before:string;after:string;reason:string}>;transfer_patterns:Array<{hanzi:string;pinyin:string;chunks:string[];gloss:string[];glossVi?:string[];naturalVi?:string;naturalEn:string;noteVi?:string;level:string}>}
function local(body:Body):DebriefResult{const m=getMission(body.missionId);if(!m)throw new Error("Mission not found");const session:Session={id:"debrief",missionId:m.id,status:"completed",currentState:"complete",slotsFilledMap:body.session.slotsFilledMap,turns:body.session.turns.map((t,i)=>({id:t.id||`t${i}`,role:t.role as Turn["role"],rawInput:t.rawInput,npcReplyCn:t.npcReplyCn,npcReplyVi:t.npcReplyVi,npcReplyEn:t.npcReplyEn,understood:t.understood,errorTags:t.errorTags,hintUsed:t.hintUsed,timestamp:t.timestamp||new Date().toISOString()})),hintLevel:0,startedAt:new Date().toISOString()};return generateDebrief(m,session)}
export async function POST(request:NextRequest){let body:Body;try{body=await request.json()}catch{return NextResponse.json({error:"Dữ liệu không hợp lệ"},{status:400})}const m=getMission(body.missionId);if(!m)return NextResponse.json({error:"Không tìm thấy nhiệm vụ"},{status:404});if(!isAIConfigured()||process.env.USE_RULE_ENGINE==="true")return NextResponse.json({...local(body),aiPowered:false});try{const turns=body.session.turns.map(t=>({role:t.role,input:t.npcReplyCn||t.rawInput,understood:t.understood,errorTags:t.errorTags}));const raw=await callAI(buildDebriefPrompt(m,turns,Object.keys(body.session.slotsFilledMap),body.session.hintUsageCount||0),"Hãy tạo bản nhận xét bằng tiếng Việt.");const a=parseJSON<AIOut>(raw.content);const result:DebriefResult={result:a.result,score:Math.max(0,Math.min(1,Number(a.score)||0)),strengths:a.strengths||[],topFixes:(a.top_fixes||[]).map(f=>({type:f.type,before:f.before,after:f.after,reason:f.reason})),transferPatterns:(a.transfer_patterns||[]).map((p):GlossItem=>({hanzi:p.hanzi,pinyin:p.pinyin,chunks:p.chunks||[],gloss:p.gloss||p.glossVi||[],glossVi:p.glossVi,naturalVi:p.naturalVi,naturalEn:p.naturalEn||p.naturalVi||"",noteVi:p.noteVi,level:(p.level as GlossItem["level"])||"A0"}))};return NextResponse.json({...result,aiPowered:true})}catch(e){console.error("AI debrief failed; using local",e);return NextResponse.json({...local(body),aiPowered:false})}}
